"""empty message

Revision ID: 5ef733a72780
Revises: f3cdee093c3a
Create Date: 2022-05-14 05:28:00.153209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef733a72780'
down_revision = 'f3cdee093c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analysis', 'user', ['user_id'], ['id'])
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'user_id')
    # ### end Alembic commands ###
