"""empty message

Revision ID: b16720f2bef5
Revises: 2b121e25f167
Create Date: 2022-05-14 01:32:03.430591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16720f2bef5'
down_revision = '2b121e25f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=100), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_table('analysis')
    # ### end Alembic commands ###
