"""empty message

Revision ID: e3f791d50878
Revises: b16720f2bef5
Create Date: 2022-05-14 05:22:06.702170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f791d50878'
down_revision = 'b16720f2bef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analysis', 'user', ['user_id'], ['id'])
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image_book',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'user_id')
    # ### end Alembic commands ###
